language: java
jdk:
  - openjdk8
install:
  - |
        echo "[tcms]" > ~/.tcms.conf
        echo "url = https://tcms.kiwitcms.org/xml-rpc/" >> ~/.tcms.conf
        echo "username = kiwitcms-bot" >> ~/.tcms.conf
        echo "password = $TCMS_PASSWORD" >> ~/.tcms.conf

script:
  - mvn checkstyle:checkstyle
  - ./bin/test

notifications:
  email:
    on_failure: change
    on_success: never
