name: testing

on:
  pull_request:
  push:
    branches: master

jobs:
  mvn:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: [8]
        kiwitcms-url: [tcms.kiwitcms.org, public.tenant.kiwitcms.org]

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        # This is Eclipse Temurin 8 (based on OpenJDK), see https://adoptium.net/
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Prepare ~/.tcms.conf for ${{ matrix.kiwitcms-url }}
      if: env.TCMS_PASSWORD
      run: |
          echo "[tcms]" > ~/.tcms.conf
          echo "url = https://${{ matrix.kiwitcms-url }}/xml-rpc/" >> ~/.tcms.conf
          echo "username = kiwitcms-bot" >> ~/.tcms.conf
          echo "password = ${{ secrets.TCMS_PASSWORD }}" >> ~/.tcms.conf
      env:
        TCMS_PASSWORD: ${{ secrets.TCMS_PASSWORD }}

    - name: Disable submission to ${{ matrix.kiwitcms-url }} if no permissions
      if: ${{ env.TCMS_PASSWORD == '' }}
      run: |
        sed -i "s/junit.jupiter.extensions.autodetection.enabled=true/junit.jupiter.extensions.autodetection.enabled=false/" pom.xml
      env:
        TCMS_PASSWORD: ${{ secrets.TCMS_PASSWORD }}

    - name: Execute tests
      run: |
        export TCMS_PRODUCT=$GITHUB_REPOSITORY
        # branch name or pull/123
        export TCMS_PRODUCT_VERSION=$(echo $GITHUB_REF | sed "s|refs/heads/||" | sed "s|refs/||" | sed "s|/merge||")
        # short commit number
        export TCMS_BUILD=$(echo $GITHUB_SHA | cut -c1-7)

        mvn checkstyle:checkstyle
        mvn test -B jacoco:report

    - name: Submit coverage report to codecov.io
      uses: codecov/codecov-action@v2
      with:
        files: ./target/site/jacoco/jacoco.xml
        verbose: true
